# Generated by Django 4.1.1 on 2022-09-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_logo', models.ImageField(default='default_user__image.png', upload_to='profile_pics')),
                ('company_email', models.EmailField(max_length=254)),
                ('company_details', djrichtextfield.models.RichTextField()),
                ('employes', models.IntegerField()),
                ('legal_info', models.FileField(blank=True, default=None, null=True, upload_to='legal_info')),
                ('b_model', models.FileField(blank=True, default=None, null=True, upload_to='b_model')),
                ('transaction_proof', models.FileField(blank=True, default=None, null=True, upload_to='transaction_proof')),
                ('market_cap', models.FileField(blank=True, default=None, null=True, upload_to='market_cap')),
                ('finances', models.FileField(blank=True, default=None, null=True, upload_to='finances')),
                ('other_Details', models.FileField(blank=True, default=None, null=True, upload_to='other_Details')),
                ('establishment_date', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_founder', to=settings.AUTH_USER_MODEL)),
                ('interested_investors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
                'ordering': ['-date_posted'],
            },
        ),
    ]
