# Generated by Django 4.1.1 on 2022-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_company_interested_investors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employes',
            new_name='company_employes',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='interested_investors',
            new_name='company_interested_investors',
        ),
        migrations.RemoveField(
            model_name='company',
            name='b_model',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_details',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legal_info',
        ),
        migrations.RemoveField(
            model_name='company',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='company',
            name='other_Details',
        ),
        migrations.RemoveField(
            model_name='company',
            name='transaction_proof',
        ),
        migrations.AddField(
            model_name='company',
            name='company_aquisition',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_competition',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_exname',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='company_founder_detail',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_fundamental',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_funding',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_history',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='company_hq',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='company_industry',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='company_mc',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='company',
            name='company_rev',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='company_site',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='fb_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='ig_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='li_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='tw_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
