# Generated by Django 4.1.1 on 2022-09-11 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0003_rename_employes_company_company_employes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_founder', to=settings.AUTH_USER_MODEL),
        ),
    ]
